# GitHub Pages configuration for Cobblemon IV Candy Wiki
title: "Cobblemon IV Candy Wiki"
description: "A comprehensive guide to the Cobblemon IV Candy mod for Minecraft"
baseurl: "/cobblemon-iv-candy"
url: "https://psbds.github.io"

# Use the Just the Docs theme
theme: just-the-docs

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  # jekyll-seo-tag is automatically included by just-the-docs theme

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections for better organization
collections:
  items:
    output: true
    permalink: /:collection/:name/
  recipes:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "items"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "page"

# SEO settings
author: "psbds"
social:
  name: "psbds"
  links:
    - "https://github.com/psbds"

# GitHub repository info
repository: "psbds/cobblemon-iv-candy"

# Just the Docs navigation configuration
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/psbds/cobblemon-iv-candy

# Enable search
search_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2025 psbds. Distributed under the <a href=\"https://github.com/psbds/cobblemon-iv-candy/blob/master/LICENSE\">MIT License</a>."

# Custom head includes for jQuery
head_custom_include_path: "_includes/head_custom.html"

# Navigation structure - remove nav_exclude_titles as it's not used in just-the-docs
